/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class metodosconstructores_Main */

#ifndef _Included_metodosconstructores_Main
#define _Included_metodosconstructores_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     metodosconstructores_Main
 * Method:    Constructores
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_metodosconstructores_Main_Constructores
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

