/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class capturaexcepciones_Main */

#ifndef _Included_capturaexcepciones_Main
#define _Included_capturaexcepciones_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     capturaexcepciones_Main
 * Method:    noCapturaExcepcion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_capturaexcepciones_Main_noCapturaExcepcion
  (JNIEnv *, jclass);

/*
 * Class:     capturaexcepciones_Main
 * Method:    clearExcepcion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_capturaexcepciones_Main_clearExcepcion
  (JNIEnv *, jclass);

/*
 * Class:     capturaexcepciones_Main
 * Method:    describeExcepcion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_capturaexcepciones_Main_describeExcepcion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
