/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class metodosclase_Main */

#ifndef _Included_metodosclase_Main
#define _Included_metodosclase_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     metodosclase_Main
 * Method:    LlamaImprime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_referenciaglobal_Main_LlamaImprime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

