/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cadenas_Main */

#ifndef _CADENAS_H
#define _CADENAS_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cadenas_Main
 * Method:    tomaTexto
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cadenas_Main_tomaTexto
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
