/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cadenas2_Main */

#ifndef _Included_cadenas2_Main
#define _Included_cadenas2_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cadenas2_Main
 * Method:    ModificaCadena
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cadenas2_Main_ModificaCadena
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
