/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef CALCULADORAVECTORES_H_
#define CALCULADORAVECTORES_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calculadoravectores_CalculadoraVectores
 * Method:    sumaVectores
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_calculadoravectores_CalculadoraVectores_sumaVectores
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     calculadoravectores_CalculadoraVectores
 * Method:    restaVectores
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_calculadoravectores_CalculadoraVectores_restaVectores
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     calculadoravectores_CalculadoraVectores
 * Method:    multiplicaVectores
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_calculadoravectores_CalculadoraVectores_multiplicaVectores
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     calculadoravectores_CalculadoraVectores
 * Method:    divideVectores
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_calculadoravectores_CalculadoraVectores_divideVectores
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif /*CALCULADORAVECTORES_H_*/
