/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calculo_CalculadoraJNI */

#ifndef _CALCULO_H
#define _CALCULO_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calculo_CalculadoraJNI
 * Method:    suma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculo_CalculadoraJNI_suma
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     calculo_CalculadoraJNI
 * Method:    resta
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculo_CalculadoraJNI_resta
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     calculo_CalculadoraJNI
 * Method:    producto
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculo_CalculadoraJNI_producto
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     calculo_CalculadoraJNI
 * Method:    division
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculo_CalculadoraJNI_division
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
