/*
 * frmLayouts.java
 *
 * Created on 15 de noviembre de 2006, 9:59
 */

/**
 *
 * @author  javi
 */
//import java.awt.*;
import java.awt.GridLayout;
import java.awt.BorderLayout;
import java.awt.FlowLayout;

public class frmLayouts extends javax.swing.JFrame {
    
    /** Creates new form frmLayouts */
    public frmLayouts() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelBotones = new javax.swing.JPanel();
        cmdGridLayout = new javax.swing.JButton();
        cmdFlowLayout = new javax.swing.JButton();
        cmdBorderLayout = new javax.swing.JButton();
        panelTrabajo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Layouts");
        setResizable(false);
        panelBotones.setLayout(new java.awt.GridLayout(1, 4));

        panelBotones.setMaximumSize(new java.awt.Dimension(32767, 25));
        panelBotones.setMinimumSize(new java.awt.Dimension(0, 25));
        panelBotones.setPreferredSize(new java.awt.Dimension(100, 25));
        cmdGridLayout.setFont(new java.awt.Font("Dialog", 1, 10));
        cmdGridLayout.setText("GridLayout");
        cmdGridLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGridLayoutActionPerformed(evt);
            }
        });

        panelBotones.add(cmdGridLayout);

        cmdFlowLayout.setFont(new java.awt.Font("Dialog", 1, 10));
        cmdFlowLayout.setText("FlowLayout");
        cmdFlowLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFlowLayoutActionPerformed(evt);
            }
        });

        panelBotones.add(cmdFlowLayout);

        cmdBorderLayout.setFont(new java.awt.Font("Dialog", 1, 10));
        cmdBorderLayout.setText("BorderLayout");
        cmdBorderLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorderLayoutActionPerformed(evt);
            }
        });

        panelBotones.add(cmdBorderLayout);

        getContentPane().add(panelBotones);

        jLabel1.setText("1");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setText("2");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel3.setText("3");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel4.setText("4");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel5.setText("5");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        org.jdesktop.layout.GroupLayout panelTrabajoLayout = new org.jdesktop.layout.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 454, Short.MAX_VALUE)
            .add(jLabel1)
            .add(jLabel2)
            .add(jLabel3)
            .add(jLabel4)
            .add(jLabel5)
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 275, Short.MAX_VALUE)
            .add(jLabel1)
            .add(jLabel2)
            .add(jLabel3)
            .add(jLabel4)
            .add(jLabel5)
        );
        getContentPane().add(panelTrabajo);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-454)/2, (screenSize.height-300)/2, 454, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBorderLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorderLayoutActionPerformed
        panelTrabajo.setLayout(new BorderLayout());        
        panelTrabajo.updateUI();
    }//GEN-LAST:event_cmdBorderLayoutActionPerformed

    private void cmdFlowLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFlowLayoutActionPerformed
        panelTrabajo.setLayout(new FlowLayout());
        panelTrabajo.updateUI();
    }//GEN-LAST:event_cmdFlowLayoutActionPerformed

    private void cmdGridLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGridLayoutActionPerformed
        panelTrabajo.setLayout(new GridLayout(2, 3, 5, 5));
        panelTrabajo.updateUI();
    }//GEN-LAST:event_cmdGridLayoutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLayouts().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorderLayout;
    private javax.swing.JButton cmdFlowLayout;
    private javax.swing.JButton cmdGridLayout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelTrabajo;
    // End of variables declaration//GEN-END:variables
    
}
