/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class holamundojni_Main */

#ifndef _Included_holamundojni_Main
#define _Included_holamundojni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     holamundojni_Main
 * Method:    sumavalores
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_holamundojni_Main_sumavalores
  (JNIEnv *, jobject , jint , jint );

#ifdef __cplusplus
}
#endif
#endif
