/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class metodosinstancia_Main */

#ifndef _Included_metodosinstancia_Main
#define _Included_metodosinstancia_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     metodosinstancia_Main
 * Method:    sumaC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_metodosinstancia_Main_sumaC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
